#this code syntax was adopted from: LAB5, Ruchika, July 2024.
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome()

#opening the site in chrome
driver.get("https://www.zappos.com/")
driver.maximize_window()
time.sleep(4)

#selecting the sandal category from the homepage
sandals= driver.find_element("xpath","//*[@id='main']/div/div/section[1]/div/article[3]/a")
sandals.click()
time.sleep(4)

#choosing the item
sandal = driver.find_element("xpath","//*[@id='products']/article[2]/a")
sandal.click()
time.sleep(4)

#choosing the size
size = driver.find_element("xpath","//*[@id='buyBoxForm']/div[2]/div/fieldset[1]/div/div[1]/label/span")
size.location_once_scrolled_into_view #this line was generated by POE AI
size.click()
time.sleep(4)

#adding item to cart
bag = driver.find_element("xpath","//*[@id='add-to-cart-button']")
bag.click()
time.sleep(4)

#checking out selected item
checkout = driver.find_element("xpath","/html/body/div[7]/div/div[4]/form/button")
checkout.click()
time.sleep(4)

driver.close()
